### ISSUE TITLE
Move adoption guide to individual branch

### ISSUE THREAD

**Issue by gnomeontherun** [gnomeontherun/vmware-clarity-issues#6]
### Task Details

We want to separate the adoption guide from the monorepo format and place it inside of its own branch. This will avoid complications with maintaining the project and allow it to be more easily deployed.

### Tasks

- [ ] Create `adoption` branch and move Adoption app inside of it
- [ ] Update GitHub deploy scripts
- [ ] Setup subdomain deployment with Netlify 

### Packages

Documentation
